name: Build Terminal Demo GIF

on:
  push:
    branches:
      - develop
    paths:
      - 'scripts/demo.sh'
    tags:
      - '*'

permissions:
  contents: write
  issues: read

jobs:
  terminal-demo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set Up PHP Environment
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4
          extensions: mbstring

      - name: Install Pipe Viewer (pv)
        run: |
          sudo apt install -y pv
          pv --version

      - name: Install Asciinema
        run: |
          sudo apt install -y asciinema
          asciinema --version

      - name: Make the script executable
        run: |
          chmod +x ./scripts/demo.sh

      - name: Record the script execution
        run: |
          asciinema rec --command="./scripts/demo.sh" --quiet --overwrite demo.cast

      - name: Download the prebuilt `agg` binary for Ubuntu (x86_64)
        run: |
          wget https://github.com/asciinema/agg/releases/download/v1.5.0/agg-x86_64-unknown-linux-gnu -O agg
          chmod +x agg
          sudo mv agg /usr/local/bin

      - name: Convert Cast to GIF using `agg` binary
        run: |
          agg --theme monokai --font-size 20 demo.cast demo.gif

      - name: Move demo.gif to assets folder and commit
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

          git fetch origin
          git checkout develop
          git reset --hard origin/develop

          DEMO_GIF_PATH="assets/demo.gif"

          mkdir -p assets
          if [ -f "$DEMO_GIF_PATH" ]; then
            rm "$DEMO_GIF_PATH"
          fi

          mv demo.gif "$DEMO_GIF_PATH"

          git add "$DEMO_GIF_PATH"
          git commit -m "Build and update demo.gif"
          git push origin develop
